# Claude API Configuration
CLAUDE_MODEL = "claude-3-5-sonnet-20241022"

# Survey Configuration
MAX_QUESTIONS_PER_SURVEY = 5
DEFAULT_QUESTION_MAX_TOKENS = 100
DEFAULT_ANALYSIS_MAX_TOKENS = 1000
DEFAULT_PROCESSING_MAX_TOKENS = 300

# Temperature Settings
QUESTION_GENERATION_TEMPERATURE = 0.7
ANALYSIS_TEMPERATURE = 0.5
PROCESSING_TEMPERATURE = 0.3