"""Add insight_type, tags, and supporting_evidence to Insight model

Revision ID: 0f84a47895ec
Revises: f93cd8d214c1
Create Date: 2025-08-12 19:14:26.010105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f84a47895ec'
down_revision = 'f93cd8d214c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supporting_evidence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_column('supporting_evidence')
        batch_op.drop_column('tags')
        batch_op.drop_column('insight_type')

    # ### end Alembic commands ###
