"""Add usefulness tracking to insights

Revision ID: f8d6133aea3b
Revises: 0f84a47895ec
Create Date: 2025-08-13 19:21:30.788507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d6133aea3b'
down_revision = '0f84a47895ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useful', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('marked_useful_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('generated_from_responses_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insight', schema=None) as batch_op:
        batch_op.drop_column('generated_from_responses_count')
        batch_op.drop_column('marked_useful_at')
        batch_op.drop_column('useful')

    # ### end Alembic commands ###
